sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
  - cd open.caesar.oml2.vscode.parent

install: 
  - npm install

script:
  - npm run vscode:prepublish

